### ISSUE TITLE
error while trying to run the sonarqube library from the sdp

### ISSUE THREAD

**Issue by stalin12** [boozallen/sdp-libraries#112]
Hello Steven,
I am getting below error while trying to run the sonarqube library from the sdp.

hudson.remoting.ProxyException: org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
at org.jenkinsci.plugins.workflow.steps.StepDescriptor.checkContextAvailability(StepDescriptor.java:266)
at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:263)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing

Any pointer will be helpful

**Comment by stalin12** [comment]
Resolved. Thanks
