### ISSUE TITLE
SDP v3.1 Github Enterprise on pull request issue

### ISSUE THREAD

**Issue by tomhuang12** [boozallen/sdp-libraries#140]
I am experiencing a number of issues when using github enterprise library with on_pull_request method. 
I am using JTE v2.3 and SDP v3.1.

The first error is the following:
```
[JTE][Step - git/on_merge.call(LinkedHashMap, CpsClosure2)]
[JTE][Step - git/on_pull_request.call(LinkedHashMap, CpsClosure2)]
[JTE][Step - git/git_distributions.fetch()]
[JTE][Step - sdp/getStep.call(String)]
[JTE][Step - sdp/jteVersion.lessThanOrEqualTo(String)]
[Pipeline] compareVersions
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveCollector.call() is applicable for argument types: (java.lang.String) values: [github_enterprise]
Possible solutions: wait(), any(), wait(long), any(groovy.lang.Closure), each(groovy.lang.Closure), collect()
```
I manage to resolve this by changing method name to `call` here: https://github.com/boozallen/sdp-libraries/blob/3.1/libraries/sdp/steps/getStep.groovy#L8.

The second error is the following:
```
[JTE][Step - git/on_merge.call(LinkedHashMap, CpsClosure2)]
[JTE][Step - git/on_pull_request.call(LinkedHashMap, CpsClosure2)]
[JTE][Step - git/git_distributions.fetch()]
[JTE][Step - sdp/getStep.call(String)]
[JTE][Step - sdp/jteVersion.lessThanOrEqualTo(String)]
[Pipeline] compareVersions
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveCollector.getStep() is applicable for argument types: (java.lang.String) values: [github_enterprise]
Possible solutions: getSteps(java.lang.String), hasStep(java.lang.String), getAt(java.lang.String), grep(), grep(java.lang.Object)
```
I manage to resolve this one by changing `...getStep(stepName)` to `...getSteps(stepName)` here: https://github.com/boozallen/sdp-libraries/blob/3.1/libraries/sdp/steps/getStep.groovy#L20

The third error I am not able to resolve. Here is the full stack:
```
[JTE][Step - git/on_merge.call(LinkedHashMap, CpsClosure2)]
[JTE][Step - git/on_pull_request.call(LinkedHashMap, CpsClosure2)]
[JTE][Step - git/git_distributions.fetch()]
[JTE][Step - sdp/getStep.call(String)]
[JTE][Step - sdp/jteVersion.lessThanOrEqualTo(String)]
[Pipeline] compareVersions
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.boozallen.plugins.jte.init.primitives.injectors.StepWrapper.get_source_branch() is applicable for argument types: () values: []
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at libraries.git.steps.WorkflowScript.call(WorkflowScript:14)
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.methodMissing(script16268975449511204730961.groovy:59)
	at WorkflowScript.run(WorkflowScript:6)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)
	at jdk.internal.reflect.GeneratedMethodAccessor333.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: org.boozallen.plugins.jte.init.primitives.injectors.StepWrapper.get_source_branch() is applicable for argument types: () values: []
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.methodMissing(script16268975449511204730961.groovy:61)
	at WorkflowScript.run(WorkflowScript:6)
	at ___cps.transform___(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor341.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I am suspecting some compatibility issue between JTE and SDP 3.1 on the following pieces of code but unable to identify a solution:
https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapper.groovy
https://github.com/boozallen/sdp-libraries/blob/3.1/libraries/git/steps/github_enterprise.groovy

Thank you and let me know if you need further information.

**Comment by Wayonb** [comment]
Hi, I am also hitting this issue. 
Any update on when a fix will be release?

**Comment by cokieffebah** [comment]
@tomhuang12 thanks.  your first two corrections are probably correct.  do you mind submitting a pull request?

**Comment by cokieffebah** [comment]
@Wayonb we are going through some internal team adjustments. We will provide updates after resolving staffing issues

**Comment by cokieffebah** [comment]
@tomhuang12 my short review, the last problem may be the following: look at the example config: https://boozallen.github.io/sdp-docs/sdp-libraries/3/libraries/git.html.  
```
libraries{
  git{
    github
    github_enterprise
    gitlab{
      connection (optional) = String // for gitlab_status
      job_name (optional) = String
      job_status (optional) =  "pending" or "running" or "canceled" or "failed" or "success".
    }
  }
}
```

**Comment by tomhuang12** [comment]
@cokieffebah To fix the third problem, I remember reverting back just the `git` library to 2.5 version's.

**Comment by cokieffebah** [comment]
Also @tomhuang12 , look at https://github.com/boozallen/sdp-libraries/blob/3.1/libraries/git/steps/git_distributions.groovy#L71.  Maybe check if `env.GIT_LIBRARY_DISTRUBITION` is set in your code, the code uses this value to pull the implementation (github|github_enterprise|gitlab).  So line https://github.com/boozallen/sdp-libraries/blob/3.1/libraries/git/steps/on_pull_request.groovy#L14: `def source_branch = git_distributions.fetch().get_source_branch()`, functionally is: `def source_branch = getStep(env.GIT_LIBRARY_DISTRUBITION).get_source_branch()`

**Comment by tomhuang12** [comment]
That could be it. I don't have access to the pipeline to test anymore :(

**Comment by cokieffebah** [comment]
no worries, sorry for the late response

**Comment by Wayonb** [comment]
@cokieffebah In my environment ``GIT_LIBRARY_DISTRUBITION`` seem to be correct.

GIT_LIBRARY_DISTRUBITION=github

**Comment by cokieffebah** [comment]
This change is now in main
